Get all/verified/unverified emails from ses
BerkayDur/sales-tracker-hermes pull request #71
Opened 2024-06-22 12:34 UTC by BerkayDur

Adds the functionality to get all/verified/unverified emails from ses. This is useful for the dashboard as it will allow us to access which customers have their email verified and which do not!

Closes #70

2024-06-22 13:01 UTC, A-Faris commented on .util/pylint_scores.txt
Please resolve these issues

2024-06-23 00:16 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
> +            and boto_ses_client._service_model.service_name == 'ses') #pylint: disable=protected-access
```suggestion
def is_ses(boto_ses_client: ses_client, message: str) -> bool:
    '''Returns true if ses client else false.'''
    if not (isinstance(boto_ses_client, BaseClient)
            and boto_ses_client._service_model.service_name == 'ses'): #pylint: disable=protected-access
            logging.error(f'client passed to {message} is not a boto3 ses client.'
            return []
        else: True
```

2024-06-23 00:37 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
> +    test_all_emails = get_all_ses_emails(client)
```suggestion
    test_all_emails = get_all_ses_emails(client, get_all_ses_emails, boto_ses_client.list_identities(IdentityType="EmailAddress")['Identities'])
```

2024-06-23 00:38 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
> +    test_unverified_emails = get_unverified_ses_emails(client)
```suggestion
    test_all_emails = get_all_ses_emails(client, "get_all_ses_emails",
                      boto_ses_client.list_identities(IdentityType="EmailAddress")['Identities'])
    test_verified_emails = get_verified_ses_emails(client)
    test_unverified_emails = get_unverified_ses_emails(client)
```

2024-06-23 00:42 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
> +    return list(set(all_emails) - set(verified_emails))
Delete all this

2024-06-23 00:43 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
This isn't following DRY principles. I given an example of what you could do but you could make more use of is_ses function for example adding logging into it

2024-06-23 00:46 UTC, A-Faris commented on Dashboard/utilities/test_ses_get_emails.py
> +    '''test for valid.'''
```suggestion
    '''test for a valid ses client.'''
```

2024-06-23 00:47 UTC, A-Faris commented on Dashboard/utilities/test_ses_get_emails.py
> +    '''test for valid.'''
Comments shouldn't be less descriptive than the function name

2024-06-23 00:49 UTC, A-Faris commented on Dashboard/utilities/test_ses_get_emails.py
NIce tests

2024-06-23 00:50 UTC, A-Faris requested changes
Good job, just make sure your ses_get_emails.py file is more efficient.

2024-06-23 09:20 UTC, BerkayDur commented on Dashboard/utilities/ses_get_emails.py
I see what you mean. But I think it's nice to have these functions that are a bit more explicit in their use cases as it makes it easier to use and understand what is going on, especially since they're all quite similar in functionality.

2024-06-23 09:23 UTC, BerkayDur commented on Dashboard/utilities/ses_get_emails.py
I'm going to modify this to have a single function with a simpler interface that does all 3 of the operations specified

2024-06-24 08:11 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
> +        region_name='eu-west-2'
Put this into .env

2024-06-24 08:13 UTC, A-Faris commented on Dashboard/utilities/ses_get_emails.py
> +    if method == 'unverified':
Could consider using match and case

2024-06-24 08:14 UTC, A-Faris requested changes
Just add region to .env

2024-06-24 08:16 UTC, BerkayDur commented on Dashboard/utilities/ses_get_emails.py
> +        region_name='eu-west-2'
Done!

2024-06-24 08:17 UTC, A-Faris approved these changes
Looks great

2024-06-24 08:20 UTC, merged