Split extract
BerkayDur/sales-tracker-hermes pull request #97
Opened 2024-06-24 17:34 UTC by NabihaMoh

Split the initial extract file into 3 separate files: a specific extract file for scraping from ASOS, a combined extract file that identifies the website name and executes the relevant extract file and lastly, a helpers file.

2024-06-24 22:50 UTC, A-Faris commented on .util/pylint_scores.txt
Perfect score, nice

2024-06-24 22:51 UTC, A-Faris commented on ETL/Pipeline/extract_from_asos.py
> +from datetime import datetime
```suggestion
"""Extract Script: Pulls current price and sale status from ASOS API"""

from datetime import datetime
```

2024-06-24 22:51 UTC, A-Faris commented on ETL/Pipeline/extract_from_asos.py
> +from datetime import datetime
Adding empty line makes it look neater

2024-06-24 22:52 UTC, A-Faris commented on ETL/Pipeline/extract_from_asos.py
> +        return None
Should there be logging error here?

2024-06-24 22:53 UTC, A-Faris commented on ETL/Pipeline/extract_from_asos.py
> +        raise TypeError('product_info must be of type dict')
Any logging error here?

2024-06-24 22:53 UTC, A-Faris commented on ETL/Pipeline/extract_from_asos.py
> +        raise TypeError('product_info must be of type dict')
logging error?

2024-06-24 22:54 UTC, A-Faris commented on ETL/Pipeline/extract_from_asos.py
Just a few logging errors to consider

2024-06-24 22:55 UTC, A-Faris commented on ETL/Pipeline/extract_combined.py
> +        logging.info('extract from product %s failed! for %s ',
logging.error better than logging.info here

2024-06-24 22:55 UTC, A-Faris commented on ETL/Pipeline/extract_combined.py
> +        return None
Any logging error here?

2024-06-24 22:55 UTC, A-Faris commented on ETL/Pipeline/extract_combined.py
> +        return None
Any logging error here?

2024-06-24 22:56 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +import logging
```suggestion
"""This file contains functions that are used throughout this directory"""

import logging
```

2024-06-24 22:56 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +        format='%(asctime)s - %(levelname)s - %(message)s'
Nice formatting

2024-06-24 22:57 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +    return all(key in entry for key in required_keys)
I love the efficency here

2024-06-24 22:58 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +    return isinstance(entry, dict)
Is this function actually needed? Feels too small

2024-06-24 23:00 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +            convert_product_code(entry) and has_correct_types(entry, required_keys)):
```suggestion
    if isinstance(entry, dict) and has_required_keys(entry, required_keys) and
            convert_product_code(entry) and has_correct_types(entry, required_keys):
```

2024-06-24 23:01 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +    return None
Either no space or put space there. I'm being very picky here
```suggestion

    logging.error("Entry is NOT valid")
    return None
```

2024-06-24 23:02 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +            or product['current_price'] <= product['previous_price']]
I love the efficiency here

2024-06-24 23:03 UTC, A-Faris commented on ETL/Pipeline/helpers.py
> +        return False
logging error?

2024-06-24 23:04 UTC, A-Faris commented on ETL/Pipeline/extract_combined.py
> +        logging.info("Removing erroneous / missing data")
Consider combining them

2024-06-24 23:05 UTC, A-Faris requested changes
A few logging errors and formatting to consider

2024-06-25 08:35 UTC, BerkayDur approved these changes, later dismissed
I looks good.

2024-06-25 08:36 UTC, A-Faris commented on ETL/Pipeline/extract_combined.py
> +    print(extract_price_and_sales_data(inputs))
Destroy this please

2024-06-25 08:37 UTC, A-Faris approved these changes, later dismissed
One little change but amazing otherwise

2024-06-25 08:41 UTC, A-Faris approved these changes
Good work

2024-06-25 08:41 UTC, merged